version: '3.1'
services:
  web:
    image: joomla
    volume: 
      - $PWD/html:/var/www/html
    port:
      - 8080:80
    environment:
        JOOMLA_DB_HOST: db
        JOOMLA_DB_PASSWORD: joomla
        JOOMLA_DB_USER: joomla
        JOOMLA_DB_NAME: joomla

  db:
    image: mysql:8.0
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
